package connection;

import android.support.annotation.NonNull;

/**
 * Created by Eirik on 15-Feb-18.
 */

public abstract class Point {

    protected final int id;
    protected double latitude;
    protected double longitude;
    protected String description;


    /**
     * Constructor to use for creating Point objects from server data
     * @param id The ID of the point, generated by the server
     * @param latitude Latitude of the point, in WGS84
     * @param longitude Longitude of the point, in WGS84
     * @param description Description of the point (optional)
     */
    public Point(int id,@NonNull double latitude,@NonNull double longitude, String description){
        this.id = id;
        this.latitude = latitude;
        this.longitude = longitude;
        this.description = description;
    }

    /**
     *  Constructor to use when creating a new point on the app - when ID is unknown.
     * @param latitude Latitude of the point, in WGS84
     * @param longitude Longitude of the point, in WGS84
     * @param description Description of the point (optional)
     */
    public Point(@NonNull double latitude,@NonNull double longitude, String description){
        this(-1, latitude, longitude, description);
    }

    public int getId() {
        return id;
    }

    public double getLatitude() {
        return latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public String getDescription() {
        return description;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
